### ISSUE TITLE
Test bug

### ISSUE THREAD

**Issue by a-murmann** [JohannesMP/NW_CellToxicityDB#1]
Describe the issue:
What do I expect:
<img width="398" alt="Screen Shot 2021-11-28 at 12 30 51 PM" src="https://user-images.githubusercontent.com/95185456/143781221-db09684e-6b44-4c9b-b893-90262f47dc19.png">

**Comment by JohannesMP** [comment]
I made a change now, can you test it?

**Comment by a-murmann** [comment]
yes
