### ISSUE TITLE
include miRNA count in "Download CVS"

### ISSUE THREAD

**Issue by a-murmann** [JohannesMP/NW_CellToxicityDB#2]
Describe: Currently the webpage shows columns called "miRNA" that lists the number of human microRNAs that share the same seed of the same row. When I down load the file "Download CVS" there is currently no column that lists this number. 
Please, add a column to the downloadable file that lists the number of microRNAs named.

**Comment by JohannesMP** [comment]
What would you like the header name of this to be?

Would "miRNA_count" work?

**Comment by a-murmann** [comment]
For the header use "hsa-miRNA_count".
(Note: hsa is the acronym for _Homo sapiens_, and is typically used as hsa. And at the moment we only have human miRNAs listed. Later, when we add mouse miRNAs the acronym for that will be mme for _Mus musculus_, the house mouse, and then the column header for the mouse specific miRNAs could be named "mme-miRNA_count").

**Comment by JohannesMP** [comment]
Added in 20a91c716013377b02a5e6b2ff7302c459d1fc2a
