### ISSUE TITLE
Change headers in down loadabel file

### ISSUE THREAD

**Issue by a-murmann** [JohannesMP/NW_CellToxicityDB#3]
Description: There are a few columns with the wrong headers. 
When the "Download CVS" file is down loaded, a wrong header is displayed for the listed microRNAs. 

The wrong name is "avg_brain". When you change the name, the corrected name could be "human miRNAs" or use a name that Marcus prefers (later we may want to add mouse miRNAs, that is why I would use the term human as well, and not just "miRNAs").
There are also two redundant headers that do not list any data. These column headers are called "avg_lung" and "miRNAs". Those two you can just delete, as the columns are empty of data.

Thank you :-)

**Comment by JohannesMP** [comment]
Should be resolved as of 536024c
